# Site settings
title: Chaos Creator
description: Master Magus
keywords: Death, Conquest, Famine, War
author: Esther Zerstorerisch
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://estherzerstorerisch.github.io/"
